import { Lato, Poiret_One } from 'next/font/google'

import type { Metadata } from 'next'
import './globals.css'

const poiretOne = Poiret_One({
	variable: '--font-poiret-one',
	subsets: ['latin'],
	weight: ['400'],
})

const lato = Lato({
	variable: '--font-lato',
	subsets: ['latin'],
	weight: ['400', '700', '900'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${lato.variable} ${poiretOne.variable} antialiased`}>
				{children}
			</body>
		</html>
	)
}
